# Generated by Django 4.0.5 on 2022-08-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_contact1_delete_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact1',
            new_name='contact',
        ),
    ]
