# Generated by Django 4.0.5 on 2022-08-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_rename_contact_contact1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact1',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact1',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact1',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='contact1',
            old_name='surname',
            new_name='Surname',
        ),
    ]
