# Generated by Django 4.0.5 on 2022-08-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0005_rename_message_contact1_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Subject', models.TextField(max_length=200)),
                ('Message', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
